import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import LatestUpdate from '@/components/LatestUpdate/LatestUpdate';
import OfficeInfo from '@/components/OfficeInfo/OfficeInfo';

const roboto = Roboto({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Header />
        <LatestUpdate />
        <OfficeInfo />
        {children}

        <Footer />
      </body>
    </html>
  );
}
